USE [METROCC.RU.EDOCS.DB]
GO

--new IC approver

declare @userName nvarchar(250) = 'R4\Denis.Leonov'
declare @posID int = (select PositionId from ConfigUser where UserName = @userName  )
declare @deptId int = (select DepartmentId from ConfigUser where UserName = @userName)

begin tran

INSERT INTO [dbo].[ApprovalIC]
           ([ContractTypeId]
           ,[UserPositionId]
           ,[DepartmentId])
     VALUES
         (1, @posId, @deptId)
		, (2, @posId, @deptId)
		, (4, @posId, @deptId)
		, (5, @posId, @deptId)
		, (16, @posId, @deptId)
		, (23, @posId, @deptId)
		, (24, @posId, @deptId)
		, (25, @posId, @deptId)
		, (26, @posId, @deptId)
		, (27, @posId, @deptId)
		, (30, @posId, @deptId)
		, (31, @posId, @deptId)
		, (32, @posId, @deptId)
		, (40, @posId, @deptId)
		, (44, @posId, @deptId)
		, (45, @posId, @deptId)
		, (46, @posId, @deptId)
		, (47, @posId, @deptId)
		, (48, @posId, @deptId)
		, (49, @posId, @deptId)
		, (50, @posId, @deptId)
		, (51, @posId, @deptId)
		, (52, @posId, @deptId)
		, (53, @posId, @deptId)
		, (54, @posId, @deptId)
		, (55, @posId, @deptId)
		, (56, @posId, @deptId)
		, (57, @posId, @deptId)
		, (58, @posId, @deptId)
		, (59, @posId, @deptId)
		, (60, @posId, @deptId)
		, (61, @posId, @deptId)
		, (64, @posId, @deptId)
		, (69, @posId, @deptId)
		, (70, @posId, @deptId)
		, (74, @posId, @deptId)
		, (79, @posId, @deptId)
		, (80, @posId, @deptId)
		, (82, @posId, @deptId)
		, (83, @posId, @deptId)
		, (84, @posId, @deptId)
		, (86, @posId, @deptId)
		, (87, @posId, @deptId)
		, (88, @posId, @deptId)
		, (89, @posId, @deptId)
		, (90, @posId, @deptId)
		, (95, @posId, @deptId)
		, (96, @posId, @deptId)
		, (99, @posId, @deptId)
		, (100, @posId, @deptId)
		, (101, @posId, @deptId)
		, (102, @posId, @deptId)
		, (103, @posId, @deptId)
		, (104, @posId, @deptId)
		, (105, @posId, @deptId)
		, (106, @posId, @deptId)
		, (107, @posId, @deptId)
		, (108, @posId, @deptId)
		, (109, @posId, @deptId)
		, (110, @posId, @deptId)
		, (111, @posId, @deptId)
		, (153, @posId, @deptId)
		, (154, @posId, @deptId)
		, (155, @posId, @deptId)
		, (156, @posId, @deptId)
		, (157, @posId, @deptId)
		, (158, @posId, @deptId)
		, (159, @posId, @deptId)
		, (160, @posId, @deptId)
		, (161, @posId, @deptId)
		, (162, @posId, @deptId)
		, (163, @posId, @deptId)
		, (164, @posId, @deptId)
		, (165, @posId, @deptId)
		, (166, @posId, @deptId)
		, (167, @posId, @deptId)
		, (168, @posId, @deptId)
		, (171, @posId, @deptId)
		, (175, @posId, @deptId)
		, (176, @posId, @deptId)
		, (179, @posId, @deptId)
		, (180, @posId, @deptId)
		, (181, @posId, @deptId)
		, (186, @posId, @deptId)

GO

rollback
commit
